# Generated by Django 4.2.3 on 2023-10-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_usertoken_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserToken',
            new_name='Token',
        ),
    ]
