# Generated by Django 4.2.3 on 2023-10-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_rename_usertoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
